const {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
  Footer,
  PageNumber,
  NumberFormat
} = require('docx');
const fs = require('fs');
const path = require('path');

function formatTimestamp(ms) {
  const totalSeconds = Math.floor(ms / 1000);
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;

  if (hours > 0) {
    return `${String(hours).padStart(2, '0')}:${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`;
  }
  return `${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`;
}

function timestampStringToMs(ts) {
  if (typeof ts === 'number') return ts;
  if (!ts) return 0;
  const parts = ts.split(':');
  if (parts.length === 3) {
    const [h, m, rest] = parts;
    const [s, msStr] = rest.split('.');
    return (parseInt(h) * 3600 + parseInt(m) * 60 + parseInt(s)) * 1000 + parseInt(msStr || 0);
  }
  if (parts.length === 2) {
    const [m, rest] = parts;
    const [s, msStr] = rest.split('.');
    return (parseInt(m) * 60 + parseInt(s)) * 1000 + parseInt(msStr || 0);
  }
  return parseInt(ts) || 0;
}

async function generateTranscriptDocx(transcript, metadata = {}) {
  const {
    title = 'Audio Transcriber',
    filename = 'transcript',
    language = 'unknown',
    duration = null,
    date = new Date().toLocaleDateString('es-ES'),
    outputDir = './storage/exports'
  } = metadata;

  fs.mkdirSync(outputDir, { recursive: true });

  const headerParagraphs = [
    new Paragraph({
      children: [
        new TextRun({
          text: 'Audio Transcriber',
          bold: true,
          size: 20,
          color: '666666',
          font: 'Arial'
        })
      ],
      alignment: AlignmentType.RIGHT,
      spacing: { after: 100 }
    })
  ];

  const titleParagraphs = [
    new Paragraph({
      children: [
        new TextRun({
          text: title,
          bold: true,
          size: 36,
          font: 'Arial'
        })
      ],
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 200 }
    }),
    new Paragraph({
      children: [
        new TextRun({ text: 'Fecha: ', bold: true, size: 22, font: 'Arial' }),
        new TextRun({ text: date, size: 22, font: 'Arial' })
      ],
      spacing: { after: 80 }
    }),
    new Paragraph({
      children: [
        new TextRun({ text: 'Idioma: ', bold: true, size: 22, font: 'Arial' }),
        new TextRun({ text: language, size: 22, font: 'Arial' })
      ],
      spacing: { after: 80 }
    })
  ];

  if (duration) {
    titleParagraphs.push(
      new Paragraph({
        children: [
          new TextRun({ text: 'Duración: ', bold: true, size: 22, font: 'Arial' }),
          new TextRun({ text: duration, size: 22, font: 'Arial' })
        ],
        spacing: { after: 80 }
      })
    );
  }

  titleParagraphs.push(
    new Paragraph({
      children: [
        new TextRun({ text: `Segmentos: ${transcript.segments.length}`, size: 20, color: '888888', font: 'Arial' })
      ],
      spacing: { after: 300 }
    }),
    new Paragraph({
      border: {
        bottom: { color: 'CCCCCC', space: 1, style: BorderStyle.SINGLE, size: 6 }
      },
      spacing: { after: 300 }
    })
  );

  const segmentParagraphs = [];

  for (const segment of transcript.segments) {
    const startMs = timestampStringToMs(segment.start);
    const ts = formatTimestamp(startMs);

    segmentParagraphs.push(
      new Paragraph({
        children: [
          new TextRun({
            text: `[${ts}]`,
            bold: true,
            size: 20,
            color: '2563EB',
            font: 'Courier New'
          })
        ],
        spacing: { before: 200, after: 60 }
      }),
      new Paragraph({
        children: [
          new TextRun({
            text: segment.text,
            size: 24,
            font: 'Arial'
          })
        ],
        spacing: { after: 160 }
      })
    );
  }

  const doc = new Document({
    creator: 'Audio Transcriber',
    title,
    description: 'Transcript generated by Audio Transcriber',
    sections: [{
      properties: {
        page: {
          margin: {
            top: 1440,
            right: 1440,
            bottom: 1440,
            left: 1440
          }
        }
      },
      headers: {
        default: {
          options: {
            children: headerParagraphs
          }
        }
      },
      footers: {
        default: new Footer({
          children: [
            new Paragraph({
              children: [
                new TextRun({ text: 'Generado por Audio Transcriber — ', size: 16, color: '999999', font: 'Arial' }),
                new TextRun({
                  children: [PageNumber.CURRENT],
                  size: 16,
                  color: '999999',
                  font: 'Arial'
                }),
                new TextRun({ text: ' / ', size: 16, color: '999999', font: 'Arial' }),
                new TextRun({
                  children: [PageNumber.TOTAL_PAGES],
                  size: 16,
                  color: '999999',
                  font: 'Arial'
                })
              ],
              alignment: AlignmentType.CENTER
            })
          ]
        })
      },
      children: [...titleParagraphs, ...segmentParagraphs]
    }]
  });

  const buffer = await Packer.toBuffer(doc);
  const outputPath = path.join(outputDir, `${filename}.docx`);
  fs.writeFileSync(outputPath, buffer);

  return {
    path: outputPath,
    filename: `${filename}.docx`,
    size: buffer.length,
    segmentCount: transcript.segments.length
  };
}

module.exports = { generateTranscriptDocx };
